apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
spec:
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: docker-registry.local/k8s-learn-api-v1:latest
          name: api
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: api-configuration
                  key: api.runtime.profiles
            - name: API_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-configuration
                  key: api.database.url
            - name: API_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: apidb-credentials
                  key: mariadb.username
            - name: API_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apidb-credentials
                  key: mariadb.password
          ports:
            - containerPort: 8080
              name: api
