apiVersion: apps/v1
kind: Deployment
metadata:
  name: apidb
  namespace: api
spec:
  selector:
    matchLabels:
      app: apidb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apidb
    spec:
      containers:
        - image: mariadb:10.7
          name: apidb
          env:
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: apidb-credentials
                  key: mariadb.username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apidb-credentials
                  key: mariadb.password
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: apidb-configuration
                  key: mariadb.database
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: apidb-configuration
                  key: mariadb.random_root_password
          ports:
            - containerPort: 3306
              name: apidb-port
          volumeMounts:
            - name: apidb-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: apidb-persistent-storage
          persistentVolumeClaim:
            claimName: apidb-pv-claim