apiVersion: v1
kind: PersistentVolume
metadata:
  name: apidb-pv-volume
spec:
  storageClassName: apidb-local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/k3s/api/apidb"
