{{- if not .Values.database.embedded }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-database.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.port }}
      targetPort: api-database
  selector:
    {{- include "api-server.selectorLabels" . | nindent 4 }}
    object: api-database
{{- end }}