apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
data:
  api.runtime.profiles: {{ include "api-server.runtime.profiles" . }}
  api.database.url: {{ include "api-server.database.url" . }}
