apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
type: Opaque
data:
  database.username: {{ .Values.database.username | b64enc }}
  database.password: {{ .Values.database.password | b64enc }}