# Default values for api-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

test:
  enabled: true
database:
  # possible values: mariadb, derby, h2
  provider: mariadb
  databaseName: api
  username: api
  password: password
  embedded: false
  # make sure to match provider if used!
  imageOverride:
  portOverride:
  persistence:
    enabled: true
    volumeSize: 1Gi
    storageClassName:
    volumeName:
  defaults:
    mariadb:
      image: mariadb:10.7
      port: 3306
    derby:
      image: adito/derby
      port: 1527
    h2:
      image:
      port:

image:
  repository: docker-registry.local/k8s-learn-api-v1
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  database:
    pullPolicy: IfNotPresent

service:
  app:
    type: ClusterIP
    port: 8080
  database:
    type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
