apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apidb-pv-claim
spec:
  storageClassName: ""
  volumeName: apidb-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi