apiVersion: v1
kind: PersistentVolume
metadata:
  name: apidb-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/k3s/default/apidb"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: apidb-pv-claim
    namespace: default
