apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv-volume
  namespace: docker-registry
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/k3s/docker-registry/registry"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: docker-registry-pvc
    namespace: docker-registry
