apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: docker-registry-pv-volume
  resources:
    requests:
      storage: 10Gi
