services:
  api:
    image: docker-registry.local/k8s-learn-api-v1:latest
    container_name: api-core
    restart: always
    ports:
      - 8080:8080
    networks:
      - api-net
    environment:
      - SPRING_PROFILES_ACTIVE=mariadb,test
      - API_DATABASE_USERNAME=api
      - API_DATABASE_PASSWORD=mypass
      - API_DATABASE_URL=//apidb:3306/api
    depends_on:
      apidb:
        condition: service_healthy
  apidb:
    image: mariadb:10.7
    container_name: api-db
    restart: always
    expose:
      - 3306
    networks:
      - api-net
    environment:
      - MARIADB_USER=api
      - MARIADB_PASSWORD=mypass
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_DATABASE=api
    healthcheck:
      test: mariadb-admin ping --silent --host localhost --user=$$MARIADB_USER --password=$$MARIADB_PASSWORD
      interval: 5s
      retries: 6
networks:
  api-net: